name: Test tag variables
on:
  push:
    branches:
      - master
      - dev
      - main
env:
  VER_NUM: '0.5.0'
  DEST_REPO_URL: 'https://PAT:${{ secrets.VNF_GITHUB_PAT }}@github.com/velocitynetworkfoundation/integration-helpers.git'
  DEST_REPO_API_URL: 'https://api.github.com/repos/velocitynetworkfoundation/integration-helpers/pulls'
  DEST_REPO_NAME: "integration-helpers"
  DEST_REPO_TEMP_BRANCH_NAME: "postman-update"
  DEST_REPO_BRANCH_NAME: "dev"
jobs:
  push-to-vnf:
    name: Test Tags
    runs-on: ubuntu-latest
    steps:
      - name: Show VER_NUM 1
        run: |
          echo $GITHUB_RUN_NUMBER
      - name: Show Set VER_NUM
        run: |
          echo 'VER_NUM=${{ env.VER_NUM }}${{ format('-build.{0}', env.GITHUB_SHA_SHORT) }}' >> $GITHUB_ENV
      - name: Show VER_NUM 2
        run: |
          echo $GITHUB_RUN_NUMBER
      - name: Show GITHUB_RUN_NUMBER 1
        run: |
          echo $GITHUB_RUN_NUMBER
      - name: Show GITHUB_RUN_NUMBER 2
        run: |
          echo "$GITHUB_RUN_NUMBER"
      - name: Set Image Tags Dev
        run: echo ${{ env.VER_NUM }}-build."$GITHUB_RUN_NUMBER"
        if: github.ref != 'refs/heads/dev'
      - name: Set Image Tags Main
        run: echo "latest,${{ env.VER_NUM }}"
        if: github.ref != 'refs/heads/main'
      - name: Show GITHUB_ENV
        run: echo $GITHUB_ENV
          